basePath: /
definitions:
  models.Product:
    properties:
      categoryId:
        type: integer
      id:
        type: integer
      ingredient:
        type: string
      name:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: REST API for managing products
  title: Product API
  version: "1.0"
paths:
  /products:
    delete:
      consumes:
      - application/json
      description: add by json product
      parameters:
      - description: Delete product
        in: body
        name: product
        required: true
        schema:
          $ref: '#/definitions/models.Product'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Product'
      summary: Delete a product
      tags:
      - products
    get:
      consumes:
      - application/json
      description: add by json product
      parameters:
      - description: Get a product
        in: body
        name: product
        required: true
        schema:
          $ref: '#/definitions/models.Product'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Product'
      summary: Get a product
      tags:
      - products
    post:
      consumes:
      - application/json
      description: add by json product
      parameters:
      - description: Add product
        in: body
        name: product
        required: true
        schema:
          $ref: '#/definitions/models.Product'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Product'
      summary: Create a product
      tags:
      - products
    put:
      consumes:
      - application/json
      description: add by json product
      parameters:
      - description: Update product
        in: body
        name: product
        required: true
        schema:
          $ref: '#/definitions/models.Product'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Product'
      summary: Update a product
      tags:
      - products
swagger: "2.0"
